#!/usr/bin/env python3
"""Shared audit schema for backtest/live alignment."""

from __future__ import annotations

AUDIT_FIELDS = [
    "run_id",
    "symbol",
    "strategy_seq",
    "event_type",
    "ts_local",
    "ts_exch",
    "order_id",
    "action",
    "reject_reason",
    "req_ts",
    "exch_ts",
    "resp_ts",
    "entry_latency_ns",
    "resp_latency_ns",
    "spike_flag",
    "best_bid",
    "best_ask",
    "mid",
    "fair",
    "reservation",
    "half_spread",
    "position",
    "auditlatency_ms",
    "dropped_by_latency",
    "dropped_by_api_limit",
    "pos_limit",
    "impact_cost",
    "spread_bps",
    "vol_bps",
    "inventory_score",
    "feed_latency_ns",
    "latency_signal_ms",
    "bid_size",
    "ask_size",
    "greek_delta",
    "greek_gamma",
    "greek_vega",
    "greek_theta",
    "greek_adjustment",
    "target_bid_tick",
    "target_ask_tick",
    "working_bid_tick",
    "working_ask_tick",
]

REQUIRED_ALIGNMENT_FIELDS = [
    "run_id",
    "symbol",
    "strategy_seq",
    "event_type",
    "ts_local",
    "ts_exch",
    "order_id",
    "action",
    "reject_reason",
    "req_ts",
    "exch_ts",
    "resp_ts",
    "entry_latency_ns",
    "resp_latency_ns",
    "spike_flag",
    "best_bid",
    "best_ask",
    "mid",
    "fair",
    "reservation",
    "half_spread",
    "position",
    "auditlatency_ms",
    "dropped_by_latency",
    "dropped_by_api_limit",
    "pos_limit",
    "impact_cost",
    "spread_bps",
    "vol_bps",
    "inventory_score",
]
