from __future__ import annotations

import csv
import json
from pathlib import Path

from execution_outcome_labels import run_execution_outcome_labels


def _write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def _sample_tree(tmp_path: Path) -> tuple[Path, Path]:
    sample = tmp_path / "sample"
    output = sample / "stage5"
    sidecar = sample / "t009_fixed_sidecar"
    audit_fields = [
        "run_id",
        "symbol",
        "strategy_seq",
        "event_type",
        "event_source",
        "event_seq",
        "ts_local",
        "ts_exch",
        "order_id",
        "action",
        "planned_order_id",
        "planned_action",
        "throttle_reason",
        "reject_reason",
        "best_bid",
        "best_ask",
        "mid",
        "fair",
        "reservation",
        "position",
        "inventory_score",
        "feed_latency_ns",
        "latency_signal_ms",
        "bid_size",
        "ask_size",
        "bid_top5_ticks",
        "bid_top5_qtys",
        "ask_top5_ticks",
        "ask_top5_qtys",
        "market_view_source",
        "top5_source",
        "book_view_stale_ms",
        "target_bid_tick",
        "target_ask_tick",
        "working_bid_tick",
        "working_ask_tick",
        "client_order_id",
        "exchange_order_id",
        "order_side",
        "order_price",
        "order_price_tick",
        "order_qty",
        "order_remaining_qty",
        "order_executed_qty",
        "order_status",
        "order_time_in_force",
        "lifecycle_state",
        "linked_strategy_seq",
        "linked_action",
        "linked_order_id",
        "cancel_requested",
        "cancel_request_ts",
        "cancel_ack_ts",
        "fill_ts",
        "fill_qty",
        "fill_price",
        "fill_trade_id",
        "fill_after_cancel_request",
    ]
    ns = lambda ms: 1_000_000_000 + ms * 1_000_000
    _write_csv(
        sample / "audit_live_sample.csv",
        [
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 1,
                "event_type": "decision",
                "event_source": "strategy",
                "event_seq": 1,
                "ts_local": ns(0),
                "ts_exch": ns(0),
                "best_bid": "99.9",
                "best_ask": "100.1",
                "mid": "100.0",
                "fair": "100.2",
                "reservation": "100.15",
                "position": "0.0",
                "inventory_score": "0.1",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "1.0",
                "bid_size": "2.0",
                "ask_size": "1.0",
                "bid_top5_ticks": "999|998|997|996|995",
                "bid_top5_qtys": "2|1|1|1|1",
                "ask_top5_ticks": "1001|1002|1003|1004|1005",
                "ask_top5_qtys": "1|1|1|1|1",
                "market_view_source": "live_depth",
                "top5_source": "live_depth",
                "book_view_stale_ms": "1.0",
                "target_bid_tick": "999",
                "target_ask_tick": "1001",
                "working_bid_tick": "",
                "working_ask_tick": "",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 1,
                "event_type": "order_submit_sent",
                "event_source": "strategy",
                "event_seq": 2,
                "ts_local": ns(0),
                "ts_exch": ns(0),
                "order_id": "1",
                "action": "submit_buy",
                "planned_action": "submit_buy",
                "best_bid": "99.9",
                "best_ask": "100.1",
                "mid": "100.0",
                "fair": "100.2",
                "reservation": "100.15",
                "position": "0.0",
                "inventory_score": "0.1",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "1.0",
                "bid_size": "2.0",
                "ask_size": "1.0",
                "bid_top5_ticks": "999|998|997|996|995",
                "bid_top5_qtys": "2|1|1|1|1",
                "ask_top5_ticks": "1001|1002|1003|1004|1005",
                "ask_top5_qtys": "1|1|1|1|1",
                "market_view_source": "live_depth",
                "top5_source": "live_depth",
                "book_view_stale_ms": "1.0",
                "target_bid_tick": "999",
                "target_ask_tick": "1001",
                "order_side": "buy",
                "order_price": "99.9",
                "order_price_tick": "999",
                "order_qty": "1.0",
                "lifecycle_state": "order_submit_sent",
                "linked_strategy_seq": "1",
                "linked_action": "submit_buy",
                "linked_order_id": "1",
                "cancel_requested": "0",
                "cancel_request_ts": "0",
                "cancel_ack_ts": "0",
                "fill_ts": "0",
                "fill_qty": "0.0",
                "fill_price": "0.0",
                "fill_after_cancel_request": "0",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 2,
                "event_type": "decision",
                "event_source": "strategy",
                "event_seq": 3,
                "ts_local": ns(100),
                "ts_exch": ns(100),
                "best_bid": "100.0",
                "best_ask": "100.2",
                "mid": "100.1",
                "fair": "100.25",
                "reservation": "100.2",
                "position": "1.0",
                "inventory_score": "0.2",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "1.0",
                "bid_size": "2.0",
                "ask_size": "1.0",
                "bid_top5_ticks": "1000|999|998|997|996",
                "bid_top5_qtys": "2|1|1|1|1",
                "ask_top5_ticks": "1002|1003|1004|1005|1006",
                "ask_top5_qtys": "1|1|1|1|1",
                "market_view_source": "live_depth",
                "top5_source": "live_depth",
                "book_view_stale_ms": "2.0",
                "target_bid_tick": "1000",
                "target_ask_tick": "1002",
                "working_bid_tick": "999",
                "working_ask_tick": "",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 2,
                "event_type": "fill",
                "event_source": "ws",
                "event_seq": 4,
                "ts_local": ns(100),
                "ts_exch": ns(100),
                "order_id": "1",
                "action": "fill",
                "best_bid": "100.0",
                "best_ask": "100.2",
                "mid": "100.1",
                "fair": "100.25",
                "reservation": "100.2",
                "position": "1.0",
                "inventory_score": "0.2",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "1.0",
                "bid_size": "2.0",
                "ask_size": "1.0",
                "bid_top5_ticks": "1000|999|998|997|996",
                "bid_top5_qtys": "2|1|1|1|1",
                "ask_top5_ticks": "1002|1003|1004|1005|1006",
                "ask_top5_qtys": "1|1|1|1|1",
                "order_side": "buy",
                "order_price": "99.9",
                "order_price_tick": "999",
                "order_qty": "1.0",
                "order_remaining_qty": "0.0",
                "order_executed_qty": "1.0",
                "order_status": "filled",
                "lifecycle_state": "fill",
                "linked_strategy_seq": "2",
                "linked_action": "fill",
                "linked_order_id": "1",
                "cancel_requested": "0",
                "cancel_request_ts": "0",
                "cancel_ack_ts": "0",
                "fill_ts": str(ns(100)),
                "fill_qty": "1.0",
                "fill_price": "99.9",
                "fill_trade_id": "t1",
                "fill_after_cancel_request": "0",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 3,
                "event_type": "decision",
                "event_source": "strategy",
                "event_seq": 5,
                "ts_local": ns(200),
                "ts_exch": ns(200),
                "best_bid": "100.1",
                "best_ask": "100.3",
                "mid": "100.2",
                "fair": "100.0",
                "reservation": "100.05",
                "position": "1.0",
                "inventory_score": "0.6",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "2.0",
                "bid_size": "1.0",
                "ask_size": "3.0",
                "bid_top5_ticks": "1001|1000|999|998|997",
                "bid_top5_qtys": "1|1|1|1|1",
                "ask_top5_ticks": "1003|1004|1005|1006|1007",
                "ask_top5_qtys": "3|1|1|1|1",
                "market_view_source": "live_depth",
                "top5_source": "live_depth",
                "book_view_stale_ms": "3.0",
                "target_bid_tick": "1001",
                "target_ask_tick": "1003",
                "working_bid_tick": "",
                "working_ask_tick": "",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 3,
                "event_type": "order_submit_sent",
                "event_source": "strategy",
                "event_seq": 6,
                "ts_local": ns(200),
                "ts_exch": ns(200),
                "order_id": "2",
                "action": "submit_sell",
                "planned_action": "submit_sell",
                "best_bid": "100.1",
                "best_ask": "100.3",
                "mid": "100.2",
                "fair": "100.0",
                "reservation": "100.05",
                "position": "1.0",
                "inventory_score": "0.6",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "2.0",
                "bid_size": "1.0",
                "ask_size": "3.0",
                "bid_top5_ticks": "1001|1000|999|998|997",
                "bid_top5_qtys": "1|1|1|1|1",
                "ask_top5_ticks": "1003|1004|1005|1006|1007",
                "ask_top5_qtys": "3|1|1|1|1",
                "market_view_source": "live_depth",
                "top5_source": "live_depth",
                "book_view_stale_ms": "3.0",
                "target_bid_tick": "1001",
                "target_ask_tick": "1003",
                "order_side": "sell",
                "order_price": "100.3",
                "order_price_tick": "1003",
                "order_qty": "1.0",
                "lifecycle_state": "order_submit_sent",
                "linked_strategy_seq": "3",
                "linked_action": "submit_sell",
                "linked_order_id": "2",
                "cancel_requested": "0",
                "cancel_request_ts": "0",
                "cancel_ack_ts": "0",
                "fill_ts": "0",
                "fill_qty": "0.0",
                "fill_price": "0.0",
                "fill_after_cancel_request": "0",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 4,
                "event_type": "cancel_sent",
                "event_source": "strategy",
                "event_seq": 7,
                "ts_local": ns(250),
                "ts_exch": ns(250),
                "order_id": "2",
                "action": "cancel_sent",
                "order_side": "sell",
                "order_price": "100.3",
                "order_price_tick": "1003",
                "order_qty": "1.0",
                "order_remaining_qty": "1.0",
                "order_executed_qty": "0.0",
                "order_status": "new",
                "lifecycle_state": "cancel_sent",
                "linked_strategy_seq": "4",
                "linked_action": "cancel_sent",
                "linked_order_id": "2",
                "cancel_requested": "1",
                "cancel_request_ts": str(ns(250)),
                "cancel_ack_ts": "0",
                "fill_ts": "0",
                "fill_qty": "0.0",
                "fill_price": "0.0",
                "fill_after_cancel_request": "0",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 5,
                "event_type": "decision",
                "event_source": "strategy",
                "event_seq": 8,
                "ts_local": ns(300),
                "ts_exch": ns(300),
                "best_bid": "100.2",
                "best_ask": "100.4",
                "mid": "100.3",
                "fair": "100.0",
                "reservation": "100.0",
                "position": "0.0",
                "inventory_score": "0.4",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "2.0",
                "bid_size": "1.0",
                "ask_size": "3.0",
                "bid_top5_ticks": "1002|1001|1000|999|998",
                "bid_top5_qtys": "1|1|1|1|1",
                "ask_top5_ticks": "1004|1005|1006|1007|1008",
                "ask_top5_qtys": "3|1|1|1|1",
                "market_view_source": "live_depth",
                "top5_source": "live_depth",
                "book_view_stale_ms": "3.0",
                "target_bid_tick": "1002",
                "target_ask_tick": "1004",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 5,
                "event_type": "fill",
                "event_source": "ws",
                "event_seq": 9,
                "ts_local": ns(300),
                "ts_exch": ns(300),
                "order_id": "2",
                "action": "fill",
                "best_bid": "100.2",
                "best_ask": "100.4",
                "mid": "100.3",
                "fair": "100.0",
                "reservation": "100.0",
                "position": "0.0",
                "inventory_score": "0.4",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "2.0",
                "bid_size": "1.0",
                "ask_size": "3.0",
                "bid_top5_ticks": "1002|1001|1000|999|998",
                "bid_top5_qtys": "1|1|1|1|1",
                "ask_top5_ticks": "1004|1005|1006|1007|1008",
                "ask_top5_qtys": "3|1|1|1|1",
                "order_side": "sell",
                "order_price": "100.3",
                "order_price_tick": "1003",
                "order_qty": "1.0",
                "order_remaining_qty": "0.0",
                "order_executed_qty": "1.0",
                "order_status": "filled",
                "lifecycle_state": "fill",
                "linked_strategy_seq": "5",
                "linked_action": "fill",
                "linked_order_id": "2",
                "cancel_requested": "1",
                "cancel_request_ts": str(ns(250)),
                "cancel_ack_ts": "0",
                "fill_ts": str(ns(300)),
                "fill_qty": "1.0",
                "fill_price": "100.3",
                "fill_trade_id": "t2",
                "fill_after_cancel_request": "1",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 6,
                "event_type": "decision",
                "event_source": "strategy",
                "event_seq": 10,
                "ts_local": ns(500),
                "ts_exch": ns(500),
                "best_bid": "100.0",
                "best_ask": "100.2",
                "mid": "100.1",
                "fair": "100.0",
                "reservation": "100.0",
                "position": "0.0",
                "inventory_score": "0.3",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "1.5",
                "bid_size": "1.0",
                "ask_size": "1.0",
                "bid_top5_ticks": "1000|999|998|997|996",
                "bid_top5_qtys": "1|1|1|1|1",
                "ask_top5_ticks": "1002|1003|1004|1005|1006",
                "ask_top5_qtys": "1|1|1|1|1",
                "market_view_source": "live_depth",
                "top5_source": "live_depth",
                "book_view_stale_ms": "2.0",
                "target_bid_tick": "1000",
                "target_ask_tick": "1002",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 6,
                "event_type": "order_submit_sent",
                "event_source": "strategy",
                "event_seq": 11,
                "ts_local": ns(500),
                "ts_exch": ns(500),
                "order_id": "3",
                "action": "submit_buy",
                "planned_action": "submit_buy",
                "best_bid": "100.0",
                "best_ask": "100.2",
                "mid": "100.1",
                "fair": "100.0",
                "reservation": "100.0",
                "position": "0.0",
                "inventory_score": "0.3",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "1.5",
                "bid_size": "1.0",
                "ask_size": "1.0",
                "bid_top5_ticks": "1000|999|998|997|996",
                "bid_top5_qtys": "1|1|1|1|1",
                "ask_top5_ticks": "1002|1003|1004|1005|1006",
                "ask_top5_qtys": "1|1|1|1|1",
                "market_view_source": "live_depth",
                "top5_source": "live_depth",
                "book_view_stale_ms": "2.0",
                "target_bid_tick": "1000",
                "target_ask_tick": "1002",
                "order_side": "buy",
                "order_price": "99.8",
                "order_price_tick": "998",
                "order_qty": "1.0",
                "lifecycle_state": "order_submit_sent",
                "linked_strategy_seq": "6",
                "linked_action": "submit_buy",
                "linked_order_id": "3",
                "cancel_requested": "0",
                "cancel_request_ts": "0",
                "cancel_ack_ts": "0",
                "fill_ts": "0",
                "fill_qty": "0.0",
                "fill_price": "0.0",
                "fill_after_cancel_request": "0",
            },
            {
                "run_id": "sample",
                "symbol": "BTCUSDT",
                "strategy_seq": 7,
                "event_type": "decision",
                "event_source": "strategy",
                "event_seq": 12,
                "ts_local": ns(700),
                "ts_exch": ns(700),
                "best_bid": "100.4",
                "best_ask": "100.6",
                "mid": "100.5",
                "fair": "100.6",
                "reservation": "100.55",
                "position": "0.0",
                "inventory_score": "0.2",
                "feed_latency_ns": "1000000",
                "latency_signal_ms": "1.0",
                "bid_size": "2.0",
                "ask_size": "1.0",
                "bid_top5_ticks": "1004|1003|1002|1001|1000",
                "bid_top5_qtys": "2|1|1|1|1",
                "ask_top5_ticks": "1006|1007|1008|1009|1010",
                "ask_top5_qtys": "1|1|1|1|1",
                "market_view_source": "live_depth",
                "top5_source": "live_depth",
                "book_view_stale_ms": "1.0",
                "target_bid_tick": "1004",
                "target_ask_tick": "1006",
            },
        ],
        audit_fields,
    )
    joined_fields = [
        "strategy_seq",
        "decision_ts_local",
        "decision_event_type",
        "join_key",
        "join_used_future",
        "join_missing",
        "join_stale",
        "join_gap_crossed",
        "joined_raw_seq",
        "joined_depth_u",
        "joined_bookticker_u",
        "top5_join_age_ms",
        "depth_join_age_ms",
        "bookticker_join_age_ms",
        "max_join_age_ms",
        "joined_top5_source",
    ]
    _write_csv(
        sidecar / "joined_decisions.csv",
        [
            {
                "strategy_seq": 1,
                "decision_ts_local": ns(0),
                "decision_event_type": "decision",
                "join_key": "asof",
                "join_used_future": "false",
                "join_missing": "false",
                "join_stale": "false",
                "join_gap_crossed": "false",
                "joined_raw_seq": "1",
                "joined_depth_u": "1",
                "joined_bookticker_u": "1",
                "top5_join_age_ms": "0.0",
                "depth_join_age_ms": "0.0",
                "bookticker_join_age_ms": "0.0",
                "max_join_age_ms": "0.0",
                "joined_top5_source": "top5_sidecar",
            },
            {
                "strategy_seq": 2,
                "decision_ts_local": ns(100),
                "decision_event_type": "decision",
                "join_key": "asof",
                "join_used_future": "false",
                "join_missing": "false",
                "join_stale": "false",
                "join_gap_crossed": "false",
                "joined_raw_seq": "2",
                "joined_depth_u": "2",
                "joined_bookticker_u": "2",
                "top5_join_age_ms": "1.0",
                "depth_join_age_ms": "1.0",
                "bookticker_join_age_ms": "1.0",
                "max_join_age_ms": "1.0",
                "joined_top5_source": "top5_sidecar",
            },
            {
                "strategy_seq": 3,
                "decision_ts_local": ns(200),
                "decision_event_type": "decision",
                "join_key": "asof",
                "join_used_future": "false",
                "join_missing": "false",
                "join_stale": "false",
                "join_gap_crossed": "false",
                "joined_raw_seq": "3",
                "joined_depth_u": "3",
                "joined_bookticker_u": "3",
                "top5_join_age_ms": "1.0",
                "depth_join_age_ms": "1.0",
                "bookticker_join_age_ms": "1.0",
                "max_join_age_ms": "1.0",
                "joined_top5_source": "top5_sidecar",
            },
            {
                "strategy_seq": 5,
                "decision_ts_local": ns(300),
                "decision_event_type": "decision",
                "join_key": "asof",
                "join_used_future": "false",
                "join_missing": "false",
                "join_stale": "false",
                "join_gap_crossed": "false",
                "joined_raw_seq": "4",
                "joined_depth_u": "4",
                "joined_bookticker_u": "4",
                "top5_join_age_ms": "1.0",
                "depth_join_age_ms": "1.0",
                "bookticker_join_age_ms": "1.0",
                "max_join_age_ms": "1.0",
                "joined_top5_source": "top5_sidecar",
            },
            {
                "strategy_seq": 6,
                "decision_ts_local": ns(500),
                "decision_event_type": "decision",
                "join_key": "asof",
                "join_used_future": "false",
                "join_missing": "false",
                "join_stale": "false",
                "join_gap_crossed": "false",
                "joined_raw_seq": "5",
                "joined_depth_u": "5",
                "joined_bookticker_u": "5",
                "top5_join_age_ms": "1.0",
                "depth_join_age_ms": "1.0",
                "bookticker_join_age_ms": "1.0",
                "max_join_age_ms": "1.0",
                "joined_top5_source": "top5_sidecar",
            },
            {
                "strategy_seq": 7,
                "decision_ts_local": ns(700),
                "decision_event_type": "decision",
                "join_key": "asof",
                "join_used_future": "false",
                "join_missing": "false",
                "join_stale": "false",
                "join_gap_crossed": "false",
                "joined_raw_seq": "6",
                "joined_depth_u": "6",
                "joined_bookticker_u": "6",
                "top5_join_age_ms": "1.0",
                "depth_join_age_ms": "1.0",
                "bookticker_join_age_ms": "1.0",
                "max_join_age_ms": "1.0",
                "joined_top5_source": "top5_sidecar",
            },
        ],
        joined_fields,
    )
    (sample / "maker_acceptance_stage3.json").write_text(
        json.dumps({"market_view": {"classification": "passes_pricing_research_market_view"}}),
        encoding="utf-8",
    )
    (sidecar / "metrics.json").write_text(
        json.dumps({"first_valid_update_aligned": True, "depth_pu_mismatch_count": 0}),
        encoding="utf-8",
    )
    (sidecar / "joined_decisions.metrics.json").write_text(
        json.dumps(
            {
                "decision_join_coverage": 1.0,
                "future_join_count": 0,
                "join_missing_count": 0,
                "gap_crossed_join_count": 0,
                "stale_join_count": 0,
            }
        ),
        encoding="utf-8",
    )
    return sample, output


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def test_run_execution_outcome_labels_outputs_required_artifacts(tmp_path: Path) -> None:
    sample, output = _sample_tree(tmp_path)
    manifest = run_execution_outcome_labels(run_dir=sample, output_dir=output, tick_size=0.1)

    required = {
        "execution_outcome_label_summary.md",
        "execution_outcome_labels.csv",
        "label_coverage.csv",
        "label_statistics.csv",
        "fill_horizon_labels.csv",
        "fill_markout_labels.csv",
        "placement_opportunity_tradeoff.csv",
        "lifecycle_label_summary.csv",
        "censoring_summary.csv",
        "run_manifest.json",
    }
    assert required == {path.name for path in output.iterdir()}
    assert manifest["row_counts"]["submit_orders"] == 3
    assert manifest["row_counts"]["filled_orders"] == 2


def test_execution_rows_and_coverage_states(tmp_path: Path) -> None:
    sample, output = _sample_tree(tmp_path)
    run_execution_outcome_labels(run_dir=sample, output_dir=output, tick_size=0.1)

    execution_rows = _read_csv(output / "execution_outcome_labels.csv")
    by_order = {row["order_id"]: row for row in execution_rows}
    assert by_order["1"]["placement_bucket"] == "touch"
    assert by_order["1"]["fill_by_100ms"] == "1"
    assert by_order["2"]["fill_after_cancel_request"] == "1"
    assert by_order["2"]["cancel_to_fill_delay_ms"] == "50.0"
    assert by_order["3"]["placement_bucket"] == "step_back_gt1"
    assert by_order["3"]["fill_by_5000ms"] == "0"
    assert by_order["3"]["horizon_observable_5000ms"] == "0"

    coverage_rows = _read_csv(output / "label_coverage.csv")
    coverage = {row["label_class"]: row for row in coverage_rows}
    assert coverage["queue_priority_proxy"]["status"] == "observed_only_proxy"
    assert coverage["missed_fill_opportunity_cost"]["status"] == "observed_only_proxy"
    assert coverage["tail_risk"]["status"] == "low_sample"
    assert coverage["fill_probability"]["status"] == "available"


def test_fill_horizon_and_markout_labels(tmp_path: Path) -> None:
    sample, output = _sample_tree(tmp_path)
    run_execution_outcome_labels(run_dir=sample, output_dir=output, tick_size=0.1)

    horizon_rows = _read_csv(output / "fill_horizon_labels.csv")
    markout_rows = _read_csv(output / "fill_markout_labels.csv")
    order3_100 = next(row for row in horizon_rows if row["order_id"] == "3" and row["horizon_ms"] == "100")
    assert order3_100["missed_favorable_mid_move"] == "1"
    assert float(order3_100["opportunity_cost_proxy_ticks"]) > 0.0

    order1_100 = next(row for row in markout_rows if row["order_id"] == "1" and row["horizon_ms"] == "100")
    assert order1_100["horizon_observable"] == "1"
    assert float(order1_100["side_adjusted_markout_ticks"]) > 0.0
