#!/usr/bin/env python3
"""Aggregate Binance-led Hyperliquid pricing-signal evidence across samples.

This task-scoped runner is offline/read-only. It consumes pricing-signal
artifacts generated by ``binance_led_pricing_signal_runner.py`` and does not
collect data, touch private/order endpoints, implement strategy behavior, run
parameter search, enable live/default-on/tiny-live behavior, or make promotion
claims.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
import subprocess
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
TASK_ID = "0601T006"
SCHEMA_VERSION = "binance_led_hyperliquid_multisample_robustness_v1"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "local_live_analysis" / "binance_led_hyperliquid_multisample_robustness_0601T006"
DEFAULT_PRICING_SIGNAL_DIRS = [
    PROJECT_ROOT / "local_live_analysis" / "binance_led_hyperliquid_pricing_signal_0601T005",
]
ALLOWLIST = [
    "binance_top5_imbalance",
    "binance_microprice_minus_mid_ticks",
    "binance_mid_move_ticks_from_prev",
    "binance_top5_bid_qty",
]
LABELS = [
    "hyperliquid_future_mid_move_ticks",
    "hyperliquid_future_microprice_minus_mid_change_ticks",
    "hyperliquid_future_top5_imbalance_change",
    "basis_future_mid_response_ticks",
    "basis_future_microprice_response_ticks",
]
ALLOWED_RECOMMENDATIONS = {
    "continue_read_only_runner_refinement",
    "needs_more_public_samples",
    "narrow_to_specific_venue_state_regime",
    "reject_for_runner_design",
}
CANONICAL_DECISION_MODE = "event"
DIAGNOSTIC_SYNTHETIC_STATUS = "diagnostic_only_synthetic_decision_grid"
CANONICAL_EVENT_STATUS = "canonical_event_mode"
BOUNDARY_FLAGS = {
    "no_private_keys": True,
    "no_private_account_endpoints": True,
    "no_order_endpoints": True,
    "no_order_lifecycle": True,
    "no_strategy_implementation": True,
    "no_live_trading_bot": True,
    "no_parameter_search": True,
    "no_default_on": True,
    "no_tiny_live": True,
    "no_promotion": True,
    "no_schema_or_connector_or_core_api_change": True,
}


def _expand(path: str | Path) -> Path:
    return Path(path).expanduser().resolve()


def _git_commit() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=PROJECT_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except Exception:
        return "unknown"
    return result.stdout.strip()


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})


def _fieldnames(rows: list[dict[str, Any]], preferred: list[str]) -> list[str]:
    extras: list[str] = []
    for row in rows:
        for key in row:
            if key not in preferred and key not in extras:
                extras.append(key)
    return preferred + extras


def _float_value(row: dict[str, str], field: str) -> float | None:
    value = row.get(field, "")
    if value == "":
        return None
    try:
        parsed = float(value)
    except ValueError:
        return None
    return parsed if math.isfinite(parsed) else None


def _format_float(value: float | None, places: int = 8) -> str:
    if value is None or not math.isfinite(value):
        return ""
    text = f"{value:.{places}f}"
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text or "0"


def _mean(values: list[float]) -> float | None:
    clean = [value for value in values if math.isfinite(value)]
    return statistics.fmean(clean) if clean else None


def _std(values: list[float]) -> float:
    clean = [value for value in values if math.isfinite(value)]
    return statistics.pstdev(clean) if len(clean) >= 2 else 0.0


def _pearson(xs: list[float], ys: list[float]) -> float:
    if len(xs) < 2 or len(xs) != len(ys):
        return 0.0
    mean_x = statistics.fmean(xs)
    mean_y = statistics.fmean(ys)
    dx = [value - mean_x for value in xs]
    dy = [value - mean_y for value in ys]
    denom_x = math.sqrt(sum(value * value for value in dx))
    denom_y = math.sqrt(sum(value * value for value in dy))
    if denom_x == 0 or denom_y == 0:
        return 0.0
    return sum(x * y for x, y in zip(dx, dy)) / (denom_x * denom_y)


def _required_paths(pricing_signal_dir: Path) -> dict[str, Path]:
    return {
        "run_manifest": pricing_signal_dir / "run_manifest.json",
        "pricing_signal_rows": pricing_signal_dir / "pricing_signal_rows.csv",
        "horizon_label_summary": pricing_signal_dir / "horizon_label_summary.csv",
        "venue_state_conditioning_summary": pricing_signal_dir / "venue_state_conditioning_summary.csv",
    }


def _ensure_required(paths: dict[str, Path]) -> None:
    missing = [f"{name}: {path}" for name, path in paths.items() if not path.exists()]
    if missing:
        raise FileNotFoundError("Missing required pricing-signal artifacts: " + "; ".join(missing))


def _sample_id(manifest: dict[str, Any], rows: list[dict[str, str]], directory: Path) -> str:
    if rows and rows[0].get("sample_id"):
        return rows[0]["sample_id"]
    source_join = manifest.get("input_dirs", {}).get("join_dir", "")
    if source_join:
        return Path(source_join).name
    return directory.name


def _load_sample(pricing_signal_dir: Path) -> dict[str, Any]:
    paths = _required_paths(pricing_signal_dir)
    _ensure_required(paths)
    manifest = _read_json(paths["run_manifest"])
    rows = _read_csv(paths["pricing_signal_rows"])
    sample_id = _sample_id(manifest, rows, pricing_signal_dir)
    sample = {
        "sample_id": sample_id,
        "pricing_signal_dir": pricing_signal_dir,
        "paths": paths,
        "manifest": manifest,
        "rows": rows,
        "horizon_rows": _read_csv(paths["horizon_label_summary"]),
        "venue_rows": _read_csv(paths["venue_state_conditioning_summary"]),
    }
    sample.update(_decision_mode_metadata(sample))
    return sample


def _safe_read_json(path: Path | None) -> dict[str, Any]:
    if path is None or not path.exists():
        return {}
    try:
        return _read_json(path)
    except (OSError, json.JSONDecodeError):
        return {}


def _source_sample_dir(sample: dict[str, Any]) -> Path | None:
    join_sample_path = sample["manifest"].get("source_artifacts", {}).get("join_sample_manifest", "")
    join_sample = _safe_read_json(Path(join_sample_path)) if join_sample_path else {}
    source_sample_dir = join_sample.get("source_sample_dir", "")
    return Path(source_sample_dir) if source_sample_dir else None


def _decision_mode_metadata(sample: dict[str, Any]) -> dict[str, Any]:
    source_dir = _source_sample_dir(sample)
    alignment_dir = source_dir / "hyperliquid_public_sample" / "alignment" if source_dir else None
    alignment_manifest_path = alignment_dir / "run_manifest.json" if alignment_dir else None
    alignment_metrics_path = alignment_dir / "metrics.json" if alignment_dir else None
    alignment_manifest = _safe_read_json(alignment_manifest_path)
    alignment_metrics = _safe_read_json(alignment_metrics_path)
    decision_mode = (
        alignment_manifest.get("decision_mode")
        or alignment_metrics.get("decision_mode")
        or "synthetic"
    )
    synthetic_decision_count = alignment_metrics.get("synthetic_decision_count", "")
    event_decision_count = alignment_metrics.get("event_decision_count", "")
    if decision_mode == CANONICAL_DECISION_MODE:
        canonical_status = CANONICAL_EVENT_STATUS
        canonical_sample = True
    elif decision_mode == "synthetic":
        canonical_status = DIAGNOSTIC_SYNTHETIC_STATUS
        canonical_sample = False
    else:
        canonical_status = "diagnostic_only_unknown_decision_mode"
        canonical_sample = False
    return {
        "source_sample_dir": str(source_dir) if source_dir else "",
        "decision_mode": decision_mode,
        "canonical_status": canonical_status,
        "canonical_sample": canonical_sample,
        "alignment_run_manifest": str(alignment_manifest_path) if alignment_manifest_path else "",
        "alignment_metrics": str(alignment_metrics_path) if alignment_metrics_path else "",
        "synthetic_decision_count": synthetic_decision_count,
        "event_decision_count": event_decision_count,
    }


def _row_delta_value(row: dict[str, str]) -> int | None:
    value = row.get("effective_future_row_delta", "")
    if value == "":
        return None
    try:
        parsed = int(float(value))
    except ValueError:
        return None
    return parsed


def _independent_horizon_count(rows: list[dict[str, str]]) -> int:
    deltas: set[int] = set()
    for row in rows:
        delta = _row_delta_value(row)
        if delta is not None:
            deltas.add(delta)
    return len(deltas)


def _horizon_delta_signatures(rows: list[dict[str, str]]) -> dict[int, set[int]]:
    signatures: dict[int, set[int]] = defaultdict(set)
    for row in rows:
        if not row.get("horizon_ms"):
            continue
        delta = _row_delta_value(row)
        if delta is not None:
            signatures[int(row["horizon_ms"])].add(delta)
    return signatures


def _build_sample_quality_matrix(samples: list[dict[str, Any]]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for sample in samples:
        manifest = sample["manifest"]
        quality = manifest.get("quality", {})
        join_quality = quality.get("source_join_quality", {})
        ages = [_float_value(row, "effective_future_age_ms") for row in sample["rows"]]
        clean_ages = [value for value in ages if value is not None]
        horizons = sorted({int(row["horizon_ms"]) for row in sample["rows"] if row.get("horizon_ms")})
        row_delta_signatures = _horizon_delta_signatures(sample["rows"])
        independent_future_row_delta_count = _independent_horizon_count(sample["rows"])
        effective_signatures = {
            horizon: {
                _format_float(_float_value(row, "effective_future_age_ms"), places=3)
                for row in sample["rows"]
                if row.get("horizon_ms") == str(horizon) and _float_value(row, "effective_future_age_ms") is not None
            }
            for horizon in horizons
        }
        aliased_horizons = sum(1 for horizon, values in effective_signatures.items() if len(values) <= 1)
        out.append(
            {
                "sample_id": sample["sample_id"],
                "pricing_signal_dir": str(sample["pricing_signal_dir"]),
                "source_join_dir": manifest.get("input_dirs", {}).get("join_dir", ""),
                "source_analysis_dir": manifest.get("input_dirs", {}).get("analysis_dir", ""),
                "source_sample_dir": sample["source_sample_dir"],
                "decision_mode": sample["decision_mode"],
                "canonical_status": sample["canonical_status"],
                "alignment_run_manifest": sample["alignment_run_manifest"],
                "alignment_metrics": sample["alignment_metrics"],
                "event_decision_count": sample["event_decision_count"],
                "synthetic_decision_count": sample["synthetic_decision_count"],
                "input_rows": manifest.get("row_counts", {}).get("input_rows", ""),
                "primary_rows": manifest.get("row_counts", {}).get("primary_rows", ""),
                "excluded_rows": manifest.get("row_counts", {}).get("excluded_rows", ""),
                "pricing_signal_rows": manifest.get("row_counts", {}).get("pricing_signal_rows", len(sample["rows"])),
                "future_join_count": join_quality.get("future_join_count", ""),
                "missing_binance_join_count": join_quality.get("missing_binance_join_count", ""),
                "primary_usable_row_count": join_quality.get("primary_usable_row_count", ""),
                "effective_future_age_ms_min": _format_float(min(clean_ages) if clean_ages else None),
                "effective_future_age_ms_mean": _format_float(_mean(clean_ages)),
                "effective_future_age_ms_max": _format_float(max(clean_ages) if clean_ages else None),
                "horizon_count": len(horizons),
                "independent_future_row_delta_count": independent_future_row_delta_count,
                "horizon_future_row_delta_groups": "|".join(
                    f"{horizon}:{','.join(str(delta) for delta in sorted(row_delta_signatures.get(horizon, set())))}"
                    for horizon in horizons
                ),
                "aliased_horizon_signature_count": aliased_horizons,
                "pricing_signal_recommendation": quality.get("recommendation", ""),
                "single_public_sample_caveat": quality.get("single_public_sample_caveat", ""),
                "quality_status": sample["canonical_status"] if sample["rows"] else "empty_pricing_signal_rows",
            }
        )
    return out


def _feature_sample_effect(
    rows: list[dict[str, str]],
    *,
    feature: str,
    horizon_ms: int,
    label: str,
) -> dict[str, Any] | None:
    z_field = f"input_{feature}_z"
    xs: list[float] = []
    ys: list[float] = []
    high: list[float] = []
    low: list[float] = []
    row_deltas: set[int] = set()
    for row in rows:
        if row.get("horizon_ms") != str(horizon_ms):
            continue
        delta = _row_delta_value(row)
        if delta is not None:
            row_deltas.add(delta)
        z = _float_value(row, z_field)
        y = _float_value(row, label)
        if z is None or y is None:
            continue
        xs.append(z)
        ys.append(y)
        if z >= 1.0:
            high.append(y)
        elif z <= -1.0:
            low.append(y)
    if len(xs) < 20:
        return None
    high_mean = _mean(high)
    low_mean = _mean(low)
    effect = None if high_mean is None or low_mean is None else high_mean - low_mean
    corr = _pearson(xs, ys)
    direction_source = effect if effect is not None else corr
    if abs(direction_source) < 1e-12:
        direction = "zero"
    elif direction_source > 0:
        direction = "positive"
    else:
        direction = "negative"
    return {
        "row_count": len(xs),
        "high_z_row_count": len(high),
        "low_z_row_count": len(low),
        "pearson_corr": corr,
        "high_z_label_mean": high_mean,
        "low_z_label_mean": low_mean,
        "high_minus_low_effect": effect,
        "direction": direction,
        "distinct_future_row_delta_count": len(row_deltas),
    }


def _build_feature_horizon_stability(samples: list[dict[str, Any]]) -> list[dict[str, Any]]:
    horizons = sorted({int(row["horizon_ms"]) for sample in samples for row in sample["rows"] if row.get("horizon_ms")})
    out: list[dict[str, Any]] = []
    for feature in ALLOWLIST:
        for horizon_ms in horizons:
            for label in LABELS:
                sample_effects: list[dict[str, Any]] = []
                for sample in samples:
                    effect = _feature_sample_effect(sample["rows"], feature=feature, horizon_ms=horizon_ms, label=label)
                    if effect is None:
                        continue
                    effect["sample_id"] = sample["sample_id"]
                    effect["decision_mode"] = sample["decision_mode"]
                    effect["canonical_status"] = sample["canonical_status"]
                    effect["canonical_sample"] = sample["canonical_sample"]
                    sample_effects.append(effect)
                canonical_effects = [effect for effect in sample_effects if effect.get("canonical_sample")]
                directions = Counter(effect["direction"] for effect in sample_effects)
                canonical_directions = Counter(effect["direction"] for effect in canonical_effects)
                non_zero = canonical_directions["positive"] + canonical_directions["negative"]
                majority_direction = "insufficient"
                consistency = 0.0
                if non_zero:
                    majority_direction = (
                        "positive"
                        if canonical_directions["positive"] >= canonical_directions["negative"]
                        else "negative"
                    )
                    consistency = max(canonical_directions["positive"], canonical_directions["negative"]) / non_zero
                effects = [
                    effect["high_minus_low_effect"]
                    for effect in canonical_effects
                    if effect.get("high_minus_low_effect") is not None
                ]
                distinct_delta_counts = [
                    int(effect.get("distinct_future_row_delta_count", 0))
                    for effect in canonical_effects
                ]
                canonical_independent_future_row_delta_count = min(distinct_delta_counts) if distinct_delta_counts else 0
                if sample_effects and not canonical_effects:
                    verdict = DIAGNOSTIC_SYNTHETIC_STATUS
                elif len(canonical_effects) < 2:
                    verdict = "single_sample_only"
                elif canonical_independent_future_row_delta_count < 1:
                    verdict = "insufficient_independent_future_row_delta"
                elif consistency >= 0.75 and effects and abs(_mean(effects) or 0.0) > 0:
                    verdict = "stable_across_samples"
                elif consistency >= 0.75:
                    verdict = "direction_stable_low_effect"
                else:
                    verdict = "unstable_across_samples"
                out.append(
                    {
                        "feature": feature,
                        "horizon_ms": horizon_ms,
                        "label": label,
                        "sample_count": len(samples),
                        "eligible_sample_count": len(sample_effects),
                        "canonical_eligible_sample_count": len(canonical_effects),
                        "canonical_independent_future_row_delta_count": canonical_independent_future_row_delta_count,
                        "majority_direction": majority_direction,
                        "direction_consistency_ratio": _format_float(consistency),
                        "positive_sample_count": canonical_directions["positive"],
                        "negative_sample_count": canonical_directions["negative"],
                        "zero_sample_count": canonical_directions["zero"],
                        "diagnostic_synthetic_sample_count": sum(
                            1 for effect in sample_effects if effect["canonical_status"] == DIAGNOSTIC_SYNTHETIC_STATUS
                        ),
                        "total_row_count": sum(int(effect["row_count"]) for effect in canonical_effects),
                        "mean_high_minus_low_effect": _format_float(_mean(effects)),
                        "std_high_minus_low_effect": _format_float(_std(effects)),
                        "mean_abs_corr": _format_float(_mean([abs(effect["pearson_corr"]) for effect in canonical_effects])),
                        "sample_effects": "|".join(
                            f"{effect['sample_id']}:{effect['canonical_status']}:{effect['direction']}:{_format_float(effect['high_minus_low_effect'])}"
                            for effect in sample_effects
                        ),
                        "stability_verdict": verdict,
                    }
                )
    return out


def _build_effective_horizon_aliasing(samples: list[dict[str, Any]]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for sample in samples:
        rows_by_horizon: dict[int, list[dict[str, str]]] = defaultdict(list)
        for row in sample["rows"]:
            if row.get("horizon_ms"):
                rows_by_horizon[int(row["horizon_ms"])].append(row)
        mean_by_horizon: dict[int, str] = {}
        for horizon_ms, rows in sorted(rows_by_horizon.items()):
            ages = [_float_value(row, "effective_future_age_ms") for row in rows]
            clean = [value for value in ages if value is not None]
            mean_key = _format_float(_mean(clean), places=3)
            mean_by_horizon[horizon_ms] = mean_key
        alias_groups: dict[str, list[int]] = defaultdict(list)
        for horizon_ms, mean_key in mean_by_horizon.items():
            alias_groups[mean_key].append(horizon_ms)
        for horizon_ms, rows in sorted(rows_by_horizon.items()):
            ages = [_float_value(row, "effective_future_age_ms") for row in rows]
            clean = [value for value in ages if value is not None]
            row_deltas = [_row_delta_value(row) for row in rows]
            clean_row_deltas = [value for value in row_deltas if value is not None]
            mean_key = mean_by_horizon[horizon_ms]
            out.append(
                {
                    "sample_id": sample["sample_id"],
                    "decision_mode": sample["decision_mode"],
                    "canonical_status": sample["canonical_status"],
                    "horizon_ms": horizon_ms,
                    "row_count": len(rows),
                    "effective_future_age_ms_min": _format_float(min(clean) if clean else None),
                    "effective_future_age_ms_mean": _format_float(_mean(clean)),
                    "effective_future_age_ms_max": _format_float(max(clean) if clean else None),
                    "effective_future_row_delta_min": min(clean_row_deltas) if clean_row_deltas else "",
                    "effective_future_row_delta_mean": _format_float(
                        _mean([float(value) for value in clean_row_deltas])
                    ),
                    "effective_future_row_delta_max": max(clean_row_deltas) if clean_row_deltas else "",
                    "distinct_future_row_delta_count": len(set(clean_row_deltas)),
                    "distinct_effective_age_count": len({_format_float(value, places=3) for value in clean}),
                    "mean_age_alias_group": ",".join(str(value) for value in alias_groups[mean_key]),
                    "aliasing_status": "aliased_with_other_nominal_horizon"
                    if len(alias_groups[mean_key]) > 1
                    else "distinct_mean_effective_age",
                }
            )
    return out


def _spread_bucket(value: float | None) -> str:
    if value is None:
        return "spread_missing"
    if value <= 10:
        return "spread_0_10_ticks"
    if value <= 20:
        return "spread_10_20_ticks"
    return "spread_gt_20_ticks"


def _build_venue_state_conditioning(samples: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, int, str, str, str], list[float]] = defaultdict(list)
    for sample in samples:
        if not sample["canonical_sample"]:
            continue
        for row in sample["rows"]:
            horizon_ms = int(row["horizon_ms"])
            quality = row.get("context_hyperliquid_context_quality", "")
            join_age = row.get("context_hyperliquid_join_age_bucket", "")
            spread = _spread_bucket(_float_value(row, "context_hyperliquid_spread_ticks"))
            value = _float_value(row, "hyperliquid_future_mid_move_ticks")
            if value is not None:
                grouped[(sample["sample_id"], horizon_ms, quality, join_age, spread)].append(value)
    out: list[dict[str, Any]] = []
    by_regime: dict[tuple[int, str, str, str], list[tuple[str, list[float]]]] = defaultdict(list)
    for (sample_id, horizon_ms, quality, join_age, spread), values in grouped.items():
        by_regime[(horizon_ms, quality, join_age, spread)].append((sample_id, values))
    for (horizon_ms, quality, join_age, spread), sample_values in sorted(by_regime.items()):
        all_values = [value for _, values in sample_values for value in values]
        out.append(
            {
                "horizon_ms": horizon_ms,
                "hyperliquid_context_quality": quality,
                "hyperliquid_join_age_bucket": join_age,
                "hyperliquid_spread_bucket": spread,
                "sample_count": len(sample_values),
                "row_count": len(all_values),
                "mean_future_mid_move_ticks": _format_float(_mean(all_values)),
                "sample_means": "|".join(f"{sample_id}:{_format_float(_mean(values))}" for sample_id, values in sample_values),
                "conditioning_status": "multi_sample_regime" if len(sample_values) >= 2 else "single_sample_regime",
            }
        )
    return out


def _recommendation(
    samples: list[dict[str, Any]],
    stability_rows: list[dict[str, Any]],
    venue_rows: list[dict[str, Any]],
) -> tuple[str, str]:
    canonical_samples = [sample for sample in samples if sample["canonical_sample"]]
    if len(canonical_samples) < 3:
        return (
            "needs_more_public_samples",
            "fewer than three canonical event-mode synchronized public samples are available",
        )
    core_rows = [
        row
        for row in stability_rows
        if row["label"] == "hyperliquid_future_mid_move_ticks"
        and int(row.get("canonical_eligible_sample_count", 0)) >= 2
        and int(row.get("canonical_independent_future_row_delta_count", 0)) >= 1
    ]
    unstable = [row for row in core_rows if row["stability_verdict"] == "unstable_across_samples"]
    stable_features = {
        row["feature"]
        for row in core_rows
        if row["stability_verdict"] in {"stable_across_samples", "direction_stable_low_effect"}
    }
    multi_sample_regimes = [row for row in venue_rows if row["conditioning_status"] == "multi_sample_regime"]
    if unstable and len(unstable) >= max(4, len(core_rows) // 2):
        return "reject_for_runner_design", "core feature/horizon rows are unstable across samples"
    if len(stable_features) == len(ALLOWLIST):
        return "continue_read_only_runner_refinement", "all allowlist features have stable multi-sample core evidence"
    if multi_sample_regimes and stable_features:
        return "narrow_to_specific_venue_state_regime", "some stable effects exist but not across the full allowlist"
    return "needs_more_public_samples", "multi-sample evidence is not yet sufficient for a stable allowlist conclusion"


def _write_recommendation(path: Path, *, recommendation: str, reason: str, sample_count: int) -> None:
    if recommendation not in ALLOWED_RECOMMENDATIONS:
        raise ValueError(f"recommendation {recommendation} is outside allowed taxonomy")
    lines = [
        "# Pricing-Signal Robustness Recommendation",
        "",
        f"Task: `{TASK_ID}`",
        "",
        "## Recommendation",
        "",
        f"- `{recommendation}`",
        f"- Reason: {reason}.",
        "",
        "## Evidence Scope",
        "",
        f"- Processed synchronized public samples: `{sample_count}`",
        "- Inputs are existing local pricing-signal artifacts only.",
        "- Canonical evidence requires Hyperliquid `decision_mode=event`; synthetic fixed-grid artifacts are diagnostic-only.",
        "- No private/order endpoints, strategy implementation, live/default-on/tiny-live, parameter search, or promotion is authorized.",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_multi_sample_robustness_artifacts(
    *,
    pricing_signal_dirs: list[str | Path],
    output_dir: str | Path,
) -> dict[str, Any]:
    resolved_output = _expand(output_dir)
    samples = [_load_sample(_expand(path)) for path in pricing_signal_dirs]
    if not samples:
        raise ValueError("at least one pricing-signal directory is required")
    sample_ids = [sample["sample_id"] for sample in samples]
    duplicates = [sample_id for sample_id, count in Counter(sample_ids).items() if count > 1]
    if duplicates:
        raise ValueError(f"duplicate sample_id values are not allowed: {duplicates}")

    sample_quality_rows = _build_sample_quality_matrix(samples)
    stability_rows = _build_feature_horizon_stability(samples)
    aliasing_rows = _build_effective_horizon_aliasing(samples)
    venue_rows = _build_venue_state_conditioning(samples)
    recommendation, reason = _recommendation(samples, stability_rows, venue_rows)
    canonical_sample_count = sum(1 for sample in samples if sample["canonical_sample"])
    diagnostic_synthetic_sample_count = sum(
        1 for sample in samples if sample["canonical_status"] == DIAGNOSTIC_SYNTHETIC_STATUS
    )

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "task_id": TASK_ID,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "git_commit": _git_commit(),
        "output_dir": str(resolved_output),
        "pricing_signal_dirs": [str(_expand(path)) for path in pricing_signal_dirs],
        "sample_count": len(samples),
        "canonical_sample_count": canonical_sample_count,
        "diagnostic_synthetic_sample_count": diagnostic_synthetic_sample_count,
        "samples": [
            {
                "sample_id": sample["sample_id"],
                "pricing_signal_dir": str(sample["pricing_signal_dir"]),
                "source_sample_dir": sample["source_sample_dir"],
                "decision_mode": sample["decision_mode"],
                "canonical_status": sample["canonical_status"],
                "alignment_run_manifest": sample["alignment_run_manifest"],
                "alignment_metrics": sample["alignment_metrics"],
                "event_decision_count": sample["event_decision_count"],
                "synthetic_decision_count": sample["synthetic_decision_count"],
                "run_manifest": str(sample["paths"]["run_manifest"]),
                "pricing_signal_rows": str(sample["paths"]["pricing_signal_rows"]),
                "source_join_dir": sample["manifest"].get("input_dirs", {}).get("join_dir", ""),
                "source_analysis_dir": sample["manifest"].get("input_dirs", {}).get("analysis_dir", ""),
                "source_contract_dir": sample["manifest"].get("input_dirs", {}).get("contract_dir", ""),
                "row_counts": sample["manifest"].get("row_counts", {}),
                "source_join_quality": sample["manifest"].get("quality", {}).get("source_join_quality", {}),
            }
            for sample in samples
        ],
        "artifacts": {
            "multi_sample_manifest": str(resolved_output / "multi_sample_manifest.json"),
            "sample_quality_matrix": str(resolved_output / "sample_quality_matrix.csv"),
            "feature_horizon_stability_across_samples": str(resolved_output / "feature_horizon_stability_across_samples.csv"),
            "effective_horizon_aliasing_by_sample": str(resolved_output / "effective_horizon_aliasing_by_sample.csv"),
            "venue_state_conditioning_across_samples": str(resolved_output / "venue_state_conditioning_across_samples.csv"),
            "pricing_signal_robustness_recommendation": str(resolved_output / "pricing_signal_robustness_recommendation.md"),
        },
        "quality": {
            "allowlist": ALLOWLIST,
            "labels": LABELS,
            "recommendation": recommendation,
            "recommendation_reason": reason,
            "allowed_recommendations": sorted(ALLOWED_RECOMMENDATIONS),
            "canonical_decision_mode": CANONICAL_DECISION_MODE,
            "synthetic_artifact_policy": DIAGNOSTIC_SYNTHETIC_STATUS,
            "needs_additional_public_samples": canonical_sample_count < 3,
        },
        "boundary_flags": BOUNDARY_FLAGS,
    }

    _write_json(resolved_output / "multi_sample_manifest.json", manifest)
    _write_csv(
        resolved_output / "sample_quality_matrix.csv",
        sample_quality_rows,
        _fieldnames(
            sample_quality_rows,
            [
                "sample_id",
                "pricing_signal_dir",
                "source_join_dir",
                "source_analysis_dir",
                "source_sample_dir",
                "decision_mode",
                "canonical_status",
                "alignment_run_manifest",
                "alignment_metrics",
                "event_decision_count",
                "synthetic_decision_count",
                "input_rows",
                "primary_rows",
                "excluded_rows",
                "pricing_signal_rows",
                "future_join_count",
                "missing_binance_join_count",
                "primary_usable_row_count",
                "effective_future_age_ms_min",
                "effective_future_age_ms_mean",
                "effective_future_age_ms_max",
                "horizon_count",
                "independent_future_row_delta_count",
                "horizon_future_row_delta_groups",
                "aliased_horizon_signature_count",
                "pricing_signal_recommendation",
                "single_public_sample_caveat",
                "quality_status",
            ],
        ),
    )
    _write_csv(resolved_output / "feature_horizon_stability_across_samples.csv", stability_rows, _fieldnames(stability_rows, []))
    _write_csv(resolved_output / "effective_horizon_aliasing_by_sample.csv", aliasing_rows, _fieldnames(aliasing_rows, []))
    _write_csv(resolved_output / "venue_state_conditioning_across_samples.csv", venue_rows, _fieldnames(venue_rows, []))
    _write_recommendation(
        resolved_output / "pricing_signal_robustness_recommendation.md",
        recommendation=recommendation,
        reason=reason,
        sample_count=len(samples),
    )
    return {
        "run_manifest": manifest,
        "sample_quality_matrix": sample_quality_rows,
        "feature_horizon_stability_across_samples": stability_rows,
        "effective_horizon_aliasing_by_sample": aliasing_rows,
        "venue_state_conditioning_across_samples": venue_rows,
        "recommendation": recommendation,
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Aggregate Binance-led Hyperliquid pricing-signal evidence across samples.")
    parser.add_argument(
        "--pricing-signal-dir",
        dest="pricing_signal_dirs",
        action="append",
        type=Path,
        help="Pricing-signal output directory. May be supplied multiple times.",
    )
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    pricing_signal_dirs = args.pricing_signal_dirs or DEFAULT_PRICING_SIGNAL_DIRS
    result = build_multi_sample_robustness_artifacts(
        pricing_signal_dirs=pricing_signal_dirs,
        output_dir=args.output_dir,
    )
    manifest = result["run_manifest"]
    print(
        json.dumps(
            {
                "task_id": TASK_ID,
                "output_dir": manifest["output_dir"],
                "sample_count": manifest["sample_count"],
                "recommendation": manifest["quality"]["recommendation"],
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
